version: '3'
services:
  api:
    build:
      context: ./assets/images
      dockerfile: php-mysqli.dockerfile
    image: php:8-apache
    ports:
      - '3274:80'
    env_file:
      - ./.env
      - ./.env.development.local
    volumes:
      - ./public/api:/var/www/html/api
